# Generated by Django 4.1.6 on 2023-07-06 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupchat', '0002_alter_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(-1), to='groupchat.group'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
        ),
    ]
